#!/usr/bin/env python3

from argparse import ArgumentParser

parser = ArgumentParser()
subparsers = parser.add_subparsers(help='sub-command help', dest="command")

subparsers.add_parser("pio")

parser_channel = subparsers.add_parser("channel")
parser_channel.add_argument("action", choices=["deploy", "rm", "rm-streamer", "describe", "nuke", "action"])
parser_channel.add_argument("rest", nargs="*")
parser_channel.add_argument("--print-only", action="store_true")
parser_channel.add_argument("-n", dest="dry_run", action="store_true")
parser_channel.add_argument("-v", dest="config_version", default="0")

parser_deploy = subparsers.add_parser("deploy")
parser_deploy.add_argument("services", nargs="*", choices=["playout", "proxy", "c2l_services", []])

parser_streamermap = subparsers.add_parser("streamermap")
parser_streamermap.add_argument("action", choices=["pull", "push"])
parser_streamermap.add_argument("environments", nargs="*", choices=["dev", "qa", "will", "rob", []])

parser_release = subparsers.add_parser("release")
parser_release.add_argument("branch")
parser_release.add_argument("environments", nargs="*", choices=["dev", "qa", "rob", []], default="none")

parser_release_notes = subparsers.add_parser("release-notes")
parser_release_notes.add_argument("branch")

args = parser.parse_args()
